spring:
  profiles:
    #表示所用配置文件为application-dev.yml
    active: local
mybatis:
  # ** 表示任意多级子目录
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.example.springboot.entity